language: generic

sudo: false

notifications:
    email: false

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - xvfb  # For mayavi headless (needed to build the gallery)

# Need to fetch a deeper clone because the default depth Travis uses (50) isn't
# enough to get the git tags so versioneer can't find the correct version
# number.
git:
    depth: 100

env:
    global: # For pushing the built docs to the fatiando/dev repo
        - secure: cXRXecOJ0LpQBPfl/CvrrvuDTQpN0zZ1mpGG4rs02yWRmRoykqzJpPNHBHZ1MWEHGwOP9QqXjuPTRPEHYBP4I9V/7uHgrd4rIg50gonyr0LdQFLL9QxsM6SMH/zHyma+hpWmg2k3ad6zBd0GFkaACtVlS/x2F8JG+W6TrU/oL+I=
    matrix:
        - PYTHON=2.7

before_install:
    # Get Miniconda from Continuum
    # Need to source the script to set the PATH variable in this environment
    # (not the scripts environment)
    - source ci/install-miniconda.sh
    - cp ci/matplotlibrc .
    # Create a conda env to install required libraries
    - conda update --yes conda
    - conda create -n testenv --yes pip python=$PYTHON
    - source activate testenv

install:
    - conda install --yes --file ci/requirements-conda.txt
    - pip install -r ci/requirements-pip.txt
    # Show installed pkg information for postmortem diagnostic
    - conda list
    # Package Fatiando and install
    - python setup.py sdist --formats=gztar
    - pip install dist/fatiando-*.tar.gz
    # Check that versioneer got the correct version. Do this in a tmp dir to
    # make sure I'm importing the installed version.
    - mkdir -p tmp
    - cd tmp; pwd
    - pwd; python -c "import fatiando; print(fatiando.__version__)"
    - cd ..; pwd

script:
    - mkdir -p tmp
    - cd tmp; pwd
    # Use the 'fatiando.test()' command to make sure we're testing an installed
    # version of the package.
    - pwd; python -c "import fatiando; assert fatiando.test(verbose=True, coverage=True) == 0, 'Tests failed'" && cp .coverage ..
    - cd ..; pwd
    - make pep8
    - bash ci/build-docs.sh

after_success:
    - coveralls
    - bash ci/update-website.sh
